on: [push]
name: Azure ARM
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure with OIDC
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_UAMI_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
               
    - name: MS Graph
      shell: pwsh
      run: |
        Install-Module Microsoft.Graph.Groups -Force
        $accessTokenString = (az account get-access-token --resource-type ms-graph | ConvertFrom-Json).accesstoken
        $accessToken = ConvertTo-SecureString -String $accessTokenString -AsPlainText -Force
        Connect-MgGraph -AccessToken $accessToken
        Get-MgGroup
