on: [push]
name: Azure ARM
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure with OIDC
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_UAMI_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Get app token for Microsoft Graph
      uses: microsoftgraph/get-app-token@v1
      id: app-token
      with:
        scope: https://graph.microsoft.com/.default
        
    - name: Get user profile from Microsoft Graph
      run: |
        curl -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" https://graph.microsoft.com/v1.0/me
    
    - name: MS Graph
      shell: pwsh
      run: |
        Install-Module Microsoft.Graph.Groups -Force
        Connect-MgGraph -AccessToken "${{ steps.app-token.outputs.token }}"
        Get-MgGroup
