on: [push]
name: Azure ARM
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure with OIDC
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_UAMI_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: MS Graph
      shell: pwsh
      run: |
        Install-Module Microsoft.Graph.Groups -Confirm
        Connect-MgGraph -Identity -ClientId 96b3641c-d1e3-49dc-9573-f3446e880a4a
        Get-MgGroup
