name: TestAzurePowerShellContainer

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-powershell
    steps:

    - name: Aquire Access Token
      id: oidc
      shell: pwsh
      run: |
        $federated_token = Invoke-WebRequest -Headers @{Authorization = "bearer $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN"} -Uri $env:ACTIONS_ID_TOKEN_REQUEST_URL"&audience=api://AzureADTokenExchange" -Method GET -UseBasicParsing | ConvertFrom-Json | Select-Object -ExpandProperty Value
        $access_token = Invoke-WebRequest -Uri "https://login.microsoftonline.com/$env:AZURE_TENANT_ID/oauth2/v2.0/token" -Method POST -Body @{
            client_id=$env:AZURE_CLIENT_ID;
            grant_type="client_credentials";
            client_assertion_type="urn:ietf:params:oauth:client-assertion-type:jwt-bearer";
            client_assertion=$federated_token
        } -UseBasicParsing | ConvertFrom-Json | Select-Object -ExpandProperty access_token
          echo "::add-mask::$access_token"
          # echo "::set-output name=GRAPH_TOKEN::$access_token"
          echo "$env:GITHUB_OUTPUT"
          echo "GRAPH_TOKEN=$access_token" >> $env:GITHUB_OUTPUT
      env:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_UAMI_CLIENT_ID }}

    - name: PSModulePath
      shell: pwsh
      env:
        ACCESS_TOKEN: ${{ steps.oidc.outputs.GRAPH_TOKEN }}
      run: |
        $env:PSModulePath -split ":"
        Get-Module Az -ListAvailable
        Connect-AzAccount -AccessToken $env:ACCESS_TOKEN # -TenantId $env:AZURE_TENANT_ID -AccountId $env:AZURE_CLIENT_ID
        Get-AzContext
        Get-AzVM -ResourceGroupName lab-rg