name: AzurePowerShellSample

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_UAMI_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: PSModulePath
      shell: pwsh
      run: |
        $env:PSModulePath -split ":"
        dir /usr/share/

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $env:PSModulePath -split ":"
          Get-Module Az -ListAvailable
          Get-Module Microsoft.Graph -ListAvailable
        azPSVersion: "latest"